// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: kyc/kycpb/kyc.proto

package kycpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Pincode       string                 `protobuf:"bytes,3,opt,name=pincode,proto3" json:"pincode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_kyc_kycpb_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kycpb_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_kyc_kycpb_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

type VerifyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     string                 `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	DateOfBirth    string                 `protobuf:"bytes,3,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	DocumentType   string                 `protobuf:"bytes,4,opt,name=documentType,proto3" json:"documentType,omitempty"`
	DocumentNumber string                 `protobuf:"bytes,5,opt,name=documentNumber,proto3" json:"documentNumber,omitempty"`
	Address        *Address               `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_kyc_kycpb_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kycpb_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_kyc_kycpb_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *VerifyRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *VerifyRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *VerifyRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *VerifyRequest) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *VerifyRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type VerifyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     string                 `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	VerificationId string                 `protobuf:"bytes,2,opt,name=verificationId,proto3" json:"verificationId,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	RiskScore      float64                `protobuf:"fixed64,4,opt,name=riskScore,proto3" json:"riskScore,omitempty"`
	VerifiedAt     string                 `protobuf:"bytes,5,opt,name=verifiedAt,proto3" json:"verifiedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_kyc_kycpb_kyc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kycpb_kyc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_kyc_kycpb_kyc_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *VerifyResponse) GetVerificationId() string {
	if x != nil {
		return x.VerificationId
	}
	return ""
}

func (x *VerifyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VerifyResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *VerifyResponse) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

var File_kyc_kycpb_kyc_proto protoreflect.FileDescriptor

const file_kyc_kycpb_kyc_proto_rawDesc = "" +
	"\n" +
	"\x13kyc/kycpb/kyc.proto\x12\x03kyc\"O\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\apincode\x18\x03 \x01(\tR\apincode\"\xe1\x01\n" +
	"\rVerifyRequest\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12 \n" +
	"\vdateOfBirth\x18\x03 \x01(\tR\vdateOfBirth\x12\"\n" +
	"\fdocumentType\x18\x04 \x01(\tR\fdocumentType\x12&\n" +
	"\x0edocumentNumber\x18\x05 \x01(\tR\x0edocumentNumber\x12&\n" +
	"\aaddress\x18\x06 \x01(\v2\f.kyc.AddressR\aaddress\"\xae\x01\n" +
	"\x0eVerifyResponse\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\tR\n" +
	"customerId\x12&\n" +
	"\x0everificationId\x18\x02 \x01(\tR\x0everificationId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\triskScore\x18\x04 \x01(\x01R\triskScore\x12\x1e\n" +
	"\n" +
	"verifiedAt\x18\x05 \x01(\tR\n" +
	"verifiedAt2?\n" +
	"\n" +
	"KycService\x121\n" +
	"\x06Verify\x12\x12.kyc.VerifyRequest\x1a\x13.kyc.VerifyResponseB\x1dZ\x1bgo_project/protos/kyc/kycpbb\x06proto3"

var (
	file_kyc_kycpb_kyc_proto_rawDescOnce sync.Once
	file_kyc_kycpb_kyc_proto_rawDescData []byte
)

func file_kyc_kycpb_kyc_proto_rawDescGZIP() []byte {
	file_kyc_kycpb_kyc_proto_rawDescOnce.Do(func() {
		file_kyc_kycpb_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyc_kycpb_kyc_proto_rawDesc), len(file_kyc_kycpb_kyc_proto_rawDesc)))
	})
	return file_kyc_kycpb_kyc_proto_rawDescData
}

var file_kyc_kycpb_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kyc_kycpb_kyc_proto_goTypes = []any{
	(*Address)(nil),        // 0: kyc.Address
	(*VerifyRequest)(nil),  // 1: kyc.VerifyRequest
	(*VerifyResponse)(nil), // 2: kyc.VerifyResponse
}
var file_kyc_kycpb_kyc_proto_depIdxs = []int32{
	0, // 0: kyc.VerifyRequest.address:type_name -> kyc.Address
	1, // 1: kyc.KycService.Verify:input_type -> kyc.VerifyRequest
	2, // 2: kyc.KycService.Verify:output_type -> kyc.VerifyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kyc_kycpb_kyc_proto_init() }
func file_kyc_kycpb_kyc_proto_init() {
	if File_kyc_kycpb_kyc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyc_kycpb_kyc_proto_rawDesc), len(file_kyc_kycpb_kyc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyc_kycpb_kyc_proto_goTypes,
		DependencyIndexes: file_kyc_kycpb_kyc_proto_depIdxs,
		MessageInfos:      file_kyc_kycpb_kyc_proto_msgTypes,
	}.Build()
	File_kyc_kycpb_kyc_proto = out.File
	file_kyc_kycpb_kyc_proto_goTypes = nil
	file_kyc_kycpb_kyc_proto_depIdxs = nil
}
