// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kyc/kycpb/kyc.proto

package kycpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KycService_Verify_FullMethodName = "/kyc.KycService/Verify"
)

// KycServiceClient is the client API for KycService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KycService is the downstream gRPC service the gateway proxies to.
// It mirrors the existing Service B JSON/HTTP contract field-for-field so
// the same request can be served over either transport.
type KycServiceClient interface {
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type kycServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKycServiceClient(cc grpc.ClientConnInterface) KycServiceClient {
	return &kycServiceClient{cc}
}

func (c *kycServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, KycService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KycServiceServer is the server API for KycService service.
// All implementations must embed UnimplementedKycServiceServer
// for forward compatibility.
//
// KycService is the downstream gRPC service the gateway proxies to.
// It mirrors the existing Service B JSON/HTTP contract field-for-field so
// the same request can be served over either transport.
type KycServiceServer interface {
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedKycServiceServer()
}

// UnimplementedKycServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKycServiceServer struct{}

func (UnimplementedKycServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedKycServiceServer) mustEmbedUnimplementedKycServiceServer() {}
func (UnimplementedKycServiceServer) testEmbeddedByValue()                    {}

// UnsafeKycServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KycServiceServer will
// result in compilation errors.
type UnsafeKycServiceServer interface {
	mustEmbedUnimplementedKycServiceServer()
}

func RegisterKycServiceServer(s grpc.ServiceRegistrar, srv KycServiceServer) {
	// If the following call panics, it indicates UnimplementedKycServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KycService_ServiceDesc, srv)
}

func _KycService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KycService_ServiceDesc is the grpc.ServiceDesc for KycService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KycService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kyc.KycService",
	HandlerType: (*KycServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _KycService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kyc/kycpb/kyc.proto",
}
